import express from "express";
import controll from "../controller/controll.js";
const router = express.Router();
import Authentication from "../middleware/UserAuth.js";
import authorizeRoles from "../middleware/Authoriz.js";
router.get("/home", authorizeRoles("user", "admin", "guest"), controll.home);
router.get("/home/all", authorizeRoles("user", "admin", "guest"), controll.get);
router.get("/user/:name",authorizeRoles("user", "admin", "guest"),controll.user);
router.post("/login",  controll.signin);
router.post("/create", Authentication, authorizeRoles("user", "admin"), controll.addUser);
router.delete("/delete/:UserId", Authentication, authorizeRoles("admin"), controll.delete);
export default router;
